version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.2 # Specifying latest version because it wasn't pulling consistently
    container_name: homepage
    environment:
      PUID: 1000  # Pi UID
      PGID: 1000  # Pi GID
    ports:
      - "3000:3000"
    volumes:
      - homepage_config:/app/config
      - type: bind
        source: /nimbus/img
        target: /app/public/images
        read_only: true
    restart: unless-stopped

volumes:
  homepage_config:
    driver: local
