services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v0.9.5 # Specifying latest version because it wasn't pulling consistently
    container_name: homepage
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - HOMEPAGE_VAR_GCAL=${HOMEPAGE_VAR_GCAL}
    ports:
      - "3000:3000"
    volumes:
      - /nimbus/config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    env_file: ".env"
