services:
    kavita:
        image: jvmilazz0/kavita:latest    # Stable branch
        container_name: kavita
        volumes:
            - /mnt/comics:/comics
            - /mnt/books:/books
            - ./data:/kavita/config     # Change './data if you want to have the config files in a different place.
                                        # /kavita/config must not be changed
        environment:
            - TZ=America/New_York
        ports:
            - "5000:5000"
        restart: unless-stopped
